### ISSUE TITLE
Multiple data sources: allow renaming default data source (feature request)

### ISSUE THREAD

**Issue by karaken12** [apache/grails-core#14634]
When using multiple data sources, there must be a default data source and it must be called 'dataSource'. In a project using several data sources, "dataSource" is not a useful semantic name. As a developer, I would like to be able to rename the default data source.

I would expect this to be a configuration parameter. There is already a GORM syntax for referring to the default data source, so I would expect that to continue to work. I would also expect an incorrectly configured system to produce an intelligible error message (see #10144 for an example of the current stack trace).

Example configuration syntax

```
dataSources:
    default: sourceTwo
    sourceOne:
        driverClassName: org.h2.Driver
        ...
    sourceTwo:
        driverClassName: org.h2.Driver
        ...
    sourceThree:
        driverClassName: org.h2.Driver
        ...
```
